import { Module, MutationTree, ActionTree, GetterTree } from 'vuex'
import { 
    MutationType, 
    IRootState, 
    I{{ entityPlural }}State, 
    initial{{ entityPlural }}State 
} from '@/models/store'
import { I{{ entityName }} } from '@/models/{{ kebabCase entityPlural }}/I{{ entityName }}'
import apiClient from '@/api-client'

// TODO: this code was autogenerated.
// Complete the implementation based on your requirements then remove this comment please.

export const mutations: MutationTree<I{{ entityPlural }}State> = {
    someMutation(state: any) {
        // TODO
    }
}

export const actions: ActionTree<I{{ entityPlural }}State, IRootState> = {
    someAction({ commit, state }) {
        // TODO
    }
}

export const getters: GetterTree<I{{ entityPlural }}State, IRootState> = {
}

const namespaced: boolean = true
const state: I{{ entityPlural }}State = initial{{ entityPlural }}State

export const {{ camelCase entityPlural }}State: Module<I{{ entityPlural }}State, IRootState> = {
    namespaced,
    state,
    getters,
    actions,
    mutations
}
