import { 
    I{{ entityPlural }}ApiClientUrls, 
    I{{ entityPlural }}ApiClient, 
    {{ entityPlural }}ApiClient 
} from '@/models/api-client/{{ kebabCase entityPlural }}/I{{ entityPlural }}ApiClient'

// TODO: this code was autogenerated.
// Complete the implementation based on your requirements then remove this comment please.

// paths to live API end-points
const urls: I{{ entityPlural }}ApiClientUrls = {
	fetch{{ entityPlural }}: '/path/to/your/real/api/and-point'
}

const {{ camelCase entityPlural }}ApiClient: I{{ entityPlural }}ApiClient = new {{ entityPlural }}ApiClient(urls)
export default {{ camelCase entityPlural }}ApiClient
