import { I{{ entityName }} } from '@/models/{{ kebabCase entityPlural }}/I{{ entityName }}'

// TODO: this code was autogenerated.
// Complete the implementation based on your requirements then remove this comment please.

export interface I{{ entityPlural }}State {
    loading: boolean
    {{ camelCase entityPlural }}: I{{{ entityName }}}[]
}

export const initial{{ entityPlural }}State: I{{ entityPlural }}State = {
    loading: false,
    {{ camelCase entityPlural }}: []
}
